In [17]:
import numpy as np

In [18]:
data = np.load('./points.npy')

FileNotFoundError: [Errno 2] No such file or directory: './points.npy'

In [3]:
print(data)

[[-23.77856525  40.3818763   -1.05380946]
 [-15.24854433  76.16540876 -13.69571853]
 [  4.31526491  53.17418488 -31.58430925]
 ...
 [-37.99667689  57.81882834 -17.55799418]
 [  1.7159814   54.01064009  -6.18640838]
 [  1.89235581  59.8009017  -18.29296116]]
